format = """\
[](bg:#030B16 fg:#c53b53)\
[󰀵 ](bg:#c53b53 fg:#090c0c)\
[](fg:#c53b53 bg:#292e42)\
$time\
[](fg:#292e42 bg:#a9b1d6)\
$directory\
[](fg:#a9b1d6 bg:#3d59a1)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#3d59a1 bg:#1b1d28)\
$character\
"""

[directory]
format = "[ $path ]($style)"
style = "fg:#1f2335 bg:#a9b1d6"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#ff007c bg:#3d59a1"

[git_status]
format = '[$all_status]($style)'
style = "fg:#ff007c bg:#3d59a1"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#ff007c bg:#3d59a1"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[](bold green) '
error_symbol = '[ ✗](#E84D44) '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1b1d28"
format = '[[ 󱑍 $time ](bg:#292e42 fg:#7aa2f7)]($style)'
